name: XcraftExperience
version: 1.1.0
main: de.xcraft.jan.xcraftexperience.XcraftExperience
api-version: 1.13

commands:
  bottle:
    description: Help Page
    aliases: [b, xpbottle, xpb]
permissions:
  xcraftexperience.check.other:
    default: op
  xcraftexperience.create:
    default: op
  xcraftexperience.check:
    default: op