name: XCraftWonderfulPotion
version: 0.0.1
main: de.xcraft.jan.xcraftwonderfulpotion.XCraftWonderfulPotion
api-version: 1.13

commands:
  bottle:
    description: Help Page
    aliases: [b, xpbottle, xpb]
permissions:
  xcraftexperience.check.other:
    default: op
  xcraftexperience.create:
    default: op
  xcraftexperience.check:
    default: op