name: XCraftWonderfulPotion
version: 0.0.1
main: de.xcraft.jan.xcraftwonderfulpotion.XCraftWonderfulPotion
api-version: 1.13

commands:
  xp:
    description: Help Page
permissions:
  xcraftexperience.check.other:
    default: op
  xcraftexperience.create:
    default: false
  xcraftexperience.check:
    default: false