name: XcraftExperience
version: 1.1.9
main: de.xcraft.jan.xcraftexperience.XcraftExperience
api-version: 1.15
authors:
- MyNameIsJan
- Umbreon

commands:
  bottle:
    description: Help Page
    aliases: [b, xpbottle, xpb]
permissions:
  xcraftexperience.help:
    default: op
  xcraftexperience.check.other:
    default: op
  xcraftexperience.create:
    default: op
  xcraftexperience.check:
    default: op
  xcraftexperience.set:
    default: op